#!/usr/bin/env bash
#this script uses an if statement to say "hi" on the 9th iteration

x=1
while [ $x -le 10 ]
do
    echo "Best School"
    if [ $x -eq 9 ]
    then
        echo "Hi"
    fi
    x=$((x+1))
done

