#!/usr/bin/env bash
#this script uses case statements to make point out unlucky numbers

x=1
while [ $x -le 20 ]
do
    echo $x
    case $x in

        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
    esac
    x=$((x+1))
done
